In [1]:
import cv2 as cv
import numpy as np

cap = cv.VideoCapture('calibration.mp4')

frameCount = int(cap.get(cv.CAP_PROP_FRAME_COUNT))
frameWidth = int(cap.get(cv.CAP_PROP_FRAME_WIDTH))
frameHeight = int(cap.get(cv.CAP_PROP_FRAME_HEIGHT))

buf = np.empty((frameCount, frameHeight, frameWidth, 3), np.dtype('uint8'))

fc = 0
ret = True

while (fc < frameCount  and ret):
    ret, buf[fc] = cap.read()
    fc += 1

cap.release()

In [2]:
buf.shape

(451, 720, 1280, 3)

In [3]:
frame_indeces = np.random.randint(0, len(buf), 15)

In [4]:
# Defining the dimensions of checkerboard
CHECKERBOARD = (6,9)
criteria = (cv.TERM_CRITERIA_EPS + cv.TERM_CRITERIA_MAX_ITER, 30, 0.001)
 
# Creating vector to store vectors of 3D points for each checkerboard image
objpoints = []
# Creating vector to store vectors of 2D points for each checkerboard image
imgpoints = [] 
 
# Defining the world coordinates for 3D points
objp = np.zeros((1, CHECKERBOARD[0] * CHECKERBOARD[1], 3), np.float32)
objp[0,:,:2] = np.mgrid[0:CHECKERBOARD[0], 0:CHECKERBOARD[1]].T.reshape(-1, 2)
prev_img_shape = None

for img in buf[frame_indeces]:
    gray = cv.cvtColor(img,cv.COLOR_BGR2GRAY)
    # Find the chess board corners
    # If desired number of corners are found in the image then ret = true
    ret, corners = cv.findChessboardCorners(gray, CHECKERBOARD, cv.CALIB_CB_ADAPTIVE_THRESH + cv.CALIB_CB_FAST_CHECK + cv.CALIB_CB_NORMALIZE_IMAGE)
     
    """
    If desired number of corner are detected,
    we refine the pixel coordinates and display 
    them on the images of checker board
    """
    if ret == True:
        objpoints.append(objp)
        # refining pixel coordinates for given 2d points.
        corners2 = cv.cornerSubPix(gray, corners, (11,11),(-1,-1), criteria)
         
        imgpoints.append(corners2)
 
        # Draw and display the corners
        img = cv.drawChessboardCorners(img, CHECKERBOARD, corners2, ret)
     
    cv.imshow('img',img)
    cv.waitKey(0)
 
cv.destroyAllWindows()
 
h,w = img.shape[:2]
 
"""
Performing camera calibration by 
passing the value of known 3D points (objpoints)
and corresponding pixel coordinates of the 
detected corners (imgpoints)
"""
ret, mtx, dist, rvecs, tvecs = cv.calibrateCamera(objpoints, imgpoints, gray.shape[::-1], None, None)
 
print("Camera matrix : \n")
print(mtx)
print("dist : \n")
print(dist)
print("rvecs : \n")
print(rvecs)
print("tvecs : \n")
print(tvecs)

Camera matrix : 

[[1.20179783e+03 0.00000000e+00 6.46299599e+02]
 [0.00000000e+00 1.19798934e+03 3.50614222e+02]
 [0.00000000e+00 0.00000000e+00 1.00000000e+00]]
dist : 

[[ 1.65174467e-01 -1.21010094e+00  2.02810171e-04 -1.83419117e-03
   2.51848646e+00]]
rvecs : 

(array([[-0.27711076],
       [-0.28467298],
       [-1.54961047]]), array([[-0.24597795],
       [-0.27689333],
       [-1.55800354]]), array([[-0.02070557],
       [-0.09528152],
       [-1.55815107]]), array([[-0.48338447],
       [-0.56451468],
       [-1.52225715]]), array([[-0.31950951],
       [-0.33963562],
       [-1.52932485]]), array([[-0.27750568],
       [-0.28030269],
       [-1.52032882]]), array([[-0.46382397],
       [-0.55020142],
       [-1.53236339]]), array([[-0.2513636 ],
       [-0.27449325],
       [-1.55265736]]), array([[-0.48045373],
       [-0.56004041],
       [-1.52313043]]), array([[-0.39308673],
       [-0.46686756],
       [-1.57138613]]), array([[-0.24893681],
       [-0.40969778],
       

In [6]:
video = cv.VideoCapture(0)


In [8]:
ret, frame = video.read()

In [9]:
video.release()